
title: Edward Bagguley
# logo: /asset/img/headshot_circle.png
# description: (text below image)
show_downloads: true
theme: jekyll-theme-minimal
# other themes - "jekyll-theme-"Architect, cayman, dinky, hacker, leap day, merlot, midnight, minima, minimal, modernist, slate, tactile, time machine

